# =========================================================================
#     This makefile was generated by
#     Bakefile 0.2.2 (http://bakefile.sourceforge.net)
#     Do not modify, all changes will be overwritten!
# =========================================================================

prefix = /usr/local
exec_prefix = ${prefix}
INSTALL = /opt/local/bin/ginstall -c
EXEEXT = 
WINDRES = 
REZ = Rez
SETFILE = SetFile
NM = nm
BK_DEPS = /Users/dctucker/Development/wxMac-2.8.7/bk-deps
srcdir = .
top_srcdir = /Users/dctucker/Development/wxMac-2.8.7
LIBS = -lz -lpthread -liconv
LDFLAGS_GUI = 
CXX = g++
CXXFLAGS = -Wall -Wundef -Wno-ctor-dtor-privacy -O2 -fno-strict-aliasing -I/opt/local/include/SDL -D_GNU_SOURCE=1 -D_THREAD_SAFE -fno-common
CPPFLAGS = -DWX_PRECOMP -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES -D_IODBC_ -I${wx_top_builddir}/lib/wx/include/mac-unicode-release-2.8 -I${top_srcdir}/include -fpascal-strings -I${top_srcdir}/src/mac/carbon/morefilex -I/Developer/Headers/FlatCarbon
LDFLAGS =  -headerpad_max_install_names -framework IOKit -framework Carbon -framework Cocoa -framework System -framework QuickTime 
WX_LIB_FLAVOUR = 
TOOLKIT = MAC
TOOLKIT_LOWERCASE = mac
TOOLKIT_VERSION = 
TOOLCHAIN_FULLNAME = mac-unicode-release-2.8
EXTRALIBS =   -framework IOKit -framework Carbon -framework Cocoa -framework System -framework QuickTime  -lz -lpthread -liconv 
EXTRALIBS_GUI = -framework WebKit
HOST_SUFFIX = 
SAMPLES_RPATH_FLAG = 
SAMPLES_RPATH_POSTLINK = $(wx_top_builddir)/change-install-names $(LIBDIRNAME) $(prefix) $@
wx_top_builddir = /Users/dctucker/Development/wxMac-2.8.7/wx-build

### Variables: ###

DESTDIR = 
WX_RELEASE = 2.8
WX_VERSION = $(WX_RELEASE).7
LIBDIRNAME = $(wx_top_builddir)/lib
ZOOMSRC_CXXFLAGS = -D__WX$(TOOLKIT)__ $(__WXUNIV_DEFINE_p) \
	$(__EXCEPTIONS_DEFINE_p) $(__RTTI_DEFINE_p) $(__THREAD_DEFINE_p) \
	-I$(srcdir) $(__DLLFLAG_p) $(CPPFLAGS) $(CXXFLAGS)
ZOOMSRC_OBJECTS =  \
	$(__zoomsrc_os2_lib_res) \
	zoomsrc_editpanel.o \
	zoomsrc_smallview.o \
	zoomsrc_prefs.o \
	zoomsrc_mainframe.o \
	zoomsrc_zoomsrc.o \
	$(__zoomsrc___win32rc)

### Conditionally set variables: ###

#CXXC = $(CXX)
CXXC = $(BK_DEPS) $(CXX)
#PORTNAME = base
PORTNAME = $(TOOLKIT_LOWERCASE)$(TOOLKIT_VERSION)
WXBASEPORT = _carbon
#WXDEBUGFLAG = d
#WXDEBUGFLAG = d
WXUNICODEFLAG = u
#WXUNIVNAME = univ
EXTRALIBS_FOR_BASE = $(EXTRALIBS)
#EXTRALIBS_FOR_BASE = $(EXTRALIBS) $(EXTRALIBS_GUI)
EXTRALIBS_FOR_GUI = $(EXTRALIBS_GUI)
#EXTRALIBS_FOR_GUI = 
__zoomsrc___mac_setfilecmd = \
	$(SETFILE) -a C zoomsrc$(EXEEXT)
__zoomsrc___mac_rezcmd = $(__MACOSX_RESOURCES_p_1)
#__WXUNIV_DEFINE_p = -D__WXUNIVERSAL__
#__WXUNIV_DEFINE_p_1 = -d __WXUNIVERSAL__
#__WXUNIV_DEFINE_p_2 = --define __WXUNIVERSAL__
#__EXCEPTIONS_DEFINE_p = -DwxNO_EXCEPTIONS
#__EXCEPTIONS_DEFINE_p_1 = -d wxNO_EXCEPTIONS
#__EXCEPTIONS_DEFINE_p_2 = --define wxNO_EXCEPTIONS
#__RTTI_DEFINE_p = -DwxNO_RTTI
#__RTTI_DEFINE_p_1 = -d wxNO_RTTI
#__RTTI_DEFINE_p_2 = --define wxNO_RTTI
#__THREAD_DEFINE_p = -DwxNO_THREADS
#__THREAD_DEFINE_p_1 = -d wxNO_THREADS
#__THREAD_DEFINE_p_2 = --define wxNO_THREADS
__DLLFLAG_p = -DWXUSINGDLL
__DLLFLAG_p_1 = -d WXUSINGDLL
__DLLFLAG_p_2 = --define WXUSINGDLL
COND_PLATFORM_OS2_1___zoomsrc___os2_emxbindcmd = $(NM) zoomsrc$(EXEEXT) | if grep -q \
	pmwin.763 ; then emxbind -ep zoomsrc$(EXEEXT) ; fi
#__zoomsrc___os2_emxbindcmd = $(COND_PLATFORM_OS2_1___zoomsrc___os2_emxbindcmd)
#__RCDEFDIR_p = -i \
#	$(LIBDIRNAME)/wx/include/$(TOOLCHAIN_FULLNAME)
#__RCDEFDIR_p_1 = --include-dir \
#	$(LIBDIRNAME)/wx/include/$(TOOLCHAIN_FULLNAME)
#__zoomsrc_os2_lib_res = \
#	$(top_srcdir)/include/wx/os2/wx.res
__zoomsrc_bundle___depname = zoomsrc_bundle
#____zoomsrc_BUNDLE_TGT_REF_DEP = \
#	zoomsrc.app/Contents/PkgInfo
____zoomsrc_BUNDLE_TGT_REF_DEP = zoomsrc.app/Contents/PkgInfo
COND_MONOLITHIC_0___WXLIB_CORE_p = \
	-lwx_$(PORTNAME)$(WXUNIVNAME)$(WXUNICODEFLAG)$(WXDEBUGFLAG)$(WX_LIB_FLAVOUR)_core-$(WX_RELEASE)$(HOST_SUFFIX)
__WXLIB_CORE_p = $(COND_MONOLITHIC_0___WXLIB_CORE_p)
COND_MONOLITHIC_0___WXLIB_BASE_p = \
	-lwx_base$(WXBASEPORT)$(WXUNICODEFLAG)$(WXDEBUGFLAG)$(WX_LIB_FLAVOUR)-$(WX_RELEASE)$(HOST_SUFFIX)
__WXLIB_BASE_p = $(COND_MONOLITHIC_0___WXLIB_BASE_p)
#__zoomsrc___win32rc = zoomsrc_zoomsrc_rc.o
COND_MONOLITHIC_1___WXLIB_MONO_p = \
	-lwx_$(PORTNAME)$(WXUNIVNAME)$(WXUNICODEFLAG)$(WXDEBUGFLAG)$(WX_LIB_FLAVOUR)-$(WX_RELEASE)$(HOST_SUFFIX)
#__WXLIB_MONO_p = $(COND_MONOLITHIC_1___WXLIB_MONO_p)
__LIB_TIFF_p \
	= \
	-lwxtiff$(WXDEBUGFLAG)$(WX_LIB_FLAVOUR)-$(WX_RELEASE)$(HOST_SUFFIX)
__LIB_JPEG_p \
	= \
	-lwxjpeg$(WXDEBUGFLAG)$(WX_LIB_FLAVOUR)-$(WX_RELEASE)$(HOST_SUFFIX)
__LIB_PNG_p \
	= \
	-lwxpng$(WXDEBUGFLAG)$(WX_LIB_FLAVOUR)-$(WX_RELEASE)$(HOST_SUFFIX)
#__LIB_ZLIB_p = \
#	-lwxzlib$(WXDEBUGFLAG)$(WX_LIB_FLAVOUR)-$(WX_RELEASE)$(HOST_SUFFIX)
#__LIB_ODBC_p = \
#	-lwxodbc$(WXDEBUGFLAG)$(WX_LIB_FLAVOUR)-$(WX_RELEASE)$(HOST_SUFFIX)
COND_WXUSE_REGEX_BUILTIN___LIB_REGEX_p = \
	-lwxregex$(WXUNICODEFLAG)$(WXDEBUGFLAG)$(WX_LIB_FLAVOUR)-$(WX_RELEASE)$(HOST_SUFFIX)
__LIB_REGEX_p = $(COND_WXUSE_REGEX_BUILTIN___LIB_REGEX_p)
#__LIB_EXPAT_p = \
#	-lwxexpat$(WXDEBUGFLAG)$(WX_LIB_FLAVOUR)-$(WX_RELEASE)$(HOST_SUFFIX)
COND_TOOLKIT_MAC___MACOSX_RESOURCES_p_1 = $(REZ) -d __DARWIN__ -t APPL -d \
	__WX$(TOOLKIT)__ $(__WXUNIV_DEFINE_p_1) $(__EXCEPTIONS_DEFINE_p_1) \
	$(__RTTI_DEFINE_p_1) $(__THREAD_DEFINE_p_1) -i $(srcdir) $(__DLLFLAG_p_1) \
	-i $(top_srcdir)/include -o \
	zoomsrc$(EXEEXT) Carbon.r icons.r
__MACOSX_RESOURCES_p_1 = $(COND_TOOLKIT_MAC___MACOSX_RESOURCES_p_1)

### Targets: ###

all: zoomsrc$(EXEEXT) $(__zoomsrc_bundle___depname)

install: all

uninstall: 

install-strip: install

clean: 
	rm -rf ./.deps ./.pch
	rm -f ./*.o
	rm -f zoomsrc$(EXEEXT)
	rm -rf zoomsrc.app

distclean: clean
	rm -f config.cache config.log config.status bk-deps bk-make-pch shared-ld-sh Makefile

zoomsrc$(EXEEXT): $(ZOOMSRC_OBJECTS) $(__zoomsrc___win32rc)
	$(CXX) -o $@ $(ZOOMSRC_OBJECTS) $(LDFLAGS)   -L$(LIBDIRNAME) $(LDFLAGS_GUI) $(SAMPLES_RPATH_FLAG)  $(LIBS) $(__WXLIB_CORE_p)  $(__WXLIB_BASE_p)  $(__WXLIB_MONO_p) $(__LIB_TIFF_p) $(__LIB_JPEG_p) $(__LIB_PNG_p) $(EXTRALIBS_FOR_GUI) $(__LIB_ZLIB_p) $(__LIB_ODBC_p) $(__LIB_REGEX_p) $(__LIB_EXPAT_p) $(EXTRALIBS_FOR_BASE)
	$(__zoomsrc___mac_rezcmd)
	$(__zoomsrc___mac_setfilecmd)
	$(__zoomsrc___os2_emxbindcmd)
	$(SAMPLES_RPATH_POSTLINK)

zoomsrc.app/Contents/PkgInfo: zoomsrc$(EXEEXT)
	echo --- BUILDING APPLICATION BUNDLE ---
	mkdir -p zoomsrc.app/Contents
	mkdir -p zoomsrc.app/Contents/MacOS
	mkdir -p zoomsrc.app/Contents/Resources
	
	sed -e "s/IDENTIFIER/`echo $(srcdir) | sed -e 's,\.\./,,g' | sed -e 's,/,.,g'`/" \
	-e "s/EXECUTABLE/zoomsrc/" \
	-e "s/VERSION/$(WX_VERSION)/" \
	$(top_srcdir)/src/mac/carbon/Info.plist.in >zoomsrc.app/Contents/Info.plist
	
	echo -n "APPL????" >zoomsrc.app/Contents/PkgInfo
	
	ln -f zoomsrc$(EXEEXT) zoomsrc.app/Contents/MacOS/zoomsrc
	
	cp -f ZoomSrc.icns zoomsrc.app/Contents/Resources/wxmac.icns

zoomsrc_bundle: $(____zoomsrc_BUNDLE_TGT_REF_DEP)

zoomsrc_zoomsrc.o: $(srcdir)/zoomsrc.cpp
	$(CXXC) -c -o $@ $(ZOOMSRC_CXXFLAGS) $(srcdir)/zoomsrc.cpp

zoomsrc_smallview.o: $(srcdir)/smallview.cpp
	$(CXXC) -c -o $@ $(ZOOMSRC_CXXFLAGS) $(srcdir)/smallview.cpp

zoomsrc_prefs.o: $(srcdir)/prefs.cpp
	$(CXXC) -c -o $@ $(ZOOMSRC_CXXFLAGS) $(srcdir)/prefs.cpp

zoomsrc_mainframe.o: $(srcdir)/mainframe.cpp
	$(CXXC) -c -o $@ $(ZOOMSRC_CXXFLAGS) $(srcdir)/mainframe.cpp

zoomsrc_editpanel.o: $(srcdir)/editpanel.cpp
	$(CXXC) -c -o $@ $(ZOOMSRC_CXXFLAGS) $(srcdir)/editpanel.cpp

zoomsrc_zoomsrc_rc.o: $(srcdir)/zoomsrc.rc
	$(WINDRES) -i$< -o$@    --define __WX$(TOOLKIT)__ $(__WXUNIV_DEFINE_p_2)  $(__EXCEPTIONS_DEFINE_p_2) $(__RTTI_DEFINE_p_2) $(__THREAD_DEFINE_p_2)   --include-dir $(srcdir) $(__DLLFLAG_p_2) --include-dir $(__RCDEFDIR_p_1) --include-dir $(top_srcdir)/include


# Include dependency info, if present:
-include .deps/*.d

.PHONY: all install uninstall clean distclean zoomsrc_bundle
